### ISSUE TITLE
crates_repository fails if a workspace contains `.` as a member

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/rules_rust#1321]
This `Cargo.toml`:

```toml
[workspace]

members = [
  ".",
  "hello-lib",
]

[package]
name = "hello-rust"
version = "0.1.0"
edition = "2018"

[dependencies]
hello-lib = { path = "hello-lib" }
hex = "0.4.2"
```

currently fails to generate a repository because of this error:
```
Error: Some manifests are not being tracked. Please add the following labels to the `manifests` key: {
    "//package:Cargo.toml",
}
```

where `package` is the package containing the above `Cargo.toml`.

We should do the path normalisation to absolute paths before filtering, and normalise out any `/./` or `/../` path segments too.
