### ISSUE TITLE
crates_repository: how to define a crate twice with a different set of features ?  

### ISSUE THREAD

**Issue by QuentinPerez** [bazelbuild/rules_rust#1609]
:wave:
Is there a way to define a crate multiple times with a different set of features ?
I tried something like that but it seems that the crate is filtered out.
crates_repository(
    ...
    packages = {
        "tonic-tls": crate.spec(
            features = ["tls"],
            package = "tonic",
            version = "0.8",
        ),
        "tonic": crate.spec(
            version = "0.8",
        ),
    }
)
❯ bazel query @crate_index//... | grep tonic
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
# no more tonic dependency
Let me know it it's the right way to do it

**Comment by UebelAndre** [comment]
Odd, I would have expected that to work. I can take a look.

**Comment by UebelAndre** [comment]
Finally got some time to look into this and this seems to actually be an error in Cargo that is not surfaced when running `cargo metadata`. Using a small repro `Cargo.toml` I can generate an error:
```toml
[package]
edition = "2018"
name = "direct"
version = "0.0.1"

[lib]
name = "direct"
path = "direct.rs"
required-features = []

[dependencies.tonic]
features = []
version = "0.8"

[dependencies.tonic-tls]
features = ["tls"]
package = "tonic"
version = "0.8"

[workspace]
members = []
resolver = "1"
```
```
the crate `direct v0.0.1 (/Users/Code/resolve-repro)` depends on crate `tonic v0.8.2` multiple times with different names
```
When splicing this manifest, `crate_universe` receives a json dump that has effectively an empty [resolve section](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html#output-format)
```json
"resolve": {
    "nodes": [
        {
            "id": "direct 0.0.1 (path+file:///Users/Code/resolve-repro)",
            "dependencies": [],
            "deps": [],
            "features": []
        }
    ],
    "root": "direct 0.0.1 (path+file:///Users/Code/resolve-repro)"
},
```

And this section is the source of truth for what to render aliases for. I think a change could be made to update [cargo_bazel::context::flat_workspace_member_deps](https://github.com/bazelbuild/rules_rust/blob/0.13.0/crate_universe/src/context.rs#L276-L394) to always include the direct package definitions for any package matching [the name of the generated crate_universe package](https://github.com/bazelbuild/rules_rust/blob/0.13.0/crate_universe/src/splicing/splicer.rs#L513) since this would more closely match user expectations.

@QuentinPerez what do you think about that?

cc @illicitonion for extra eyes.
