### ISSUE TITLE
Support `[patch]` in crate_universe when using multiple Cargo.toml's

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#1858]
Currently when using Crate Universe, if there is multiple Cargo manifests not under a single workspace, it's not possible to [override dependencies](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html) using `[patch]`. 

```starlark
crates_repository(
    name = "crate_index,
    manifests = [
        "///pkg_a:Cargo.toml",
        "///sub_pkgs/pkg_b:Cargo.toml",
        "///sub_pkgs/pkg_c:Cargo.toml",
    ],
)
```

```toml
[package]
name = "pkg_a"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
reqwest = { default-features = false, version = "0.11.4", features = ["blocking", "json", "rustls-tls"] }

[dev-dependencies]
httpmock = { default-features = false, features = ["rustls"], version = "0.6.7" }

[patch.crates-io]
isahc = { git = "https://github.com/sagebind/isahc.git", rev = "096aff7b13f4ff5bb474fdc27bc30b297a2968f6" }
````

The content `[patch.crates-io]` should be reflected in the generated outputs of `crate_index`
