### ISSUE TITLE
Regression: selects/cfg are omitted in some cases

### ISSUE THREAD

**Issue by titanous** [bazelbuild/rules_rust#1909]
`v0.20.0`, and specifically, #1885 broke our build.

A reproducer is that `notify` v5.1.0 does not build anymore for Linux with errors about missing `mio`.  In `Cargo.Bazel.lock` I see that these lines get removed from `crates.notify 5\.1\.0.common_attrs.deps.selects.cfg(target_os = \"linux\")` after the change is applied (I tested by reverting the PR and building locally).

```json
              {
                "id": "mio 0.8.5",
                "target": "mio"
              }
```

The `notify` [`Cargo.toml`](https://github.com/notify-rs/notify/blob/notify-5.1.0/notify/Cargo.toml) looks like this:

```toml
[dependencies]
bitflags = "1.0.4"
crossbeam-channel = { version = "0.5.0", optional = true }
filetime = "0.2.6"
libc = "0.2.4"
serde = { version = "1.0.89", features = ["derive"], optional = true }
walkdir = "2.2.2"

[target.'cfg(target_os="linux")'.dependencies]
inotify = { version = "0.9", default-features = false }
mio = { version = "0.8", features = ["os-ext"] }

[features]
default = ["macos_fsevent","crossbeam-channel"]
timing_tests = []
manual_tests = []
macos_kqueue = ["kqueue", "mio"]
macos_fsevent = ["fsevent-sys"]
```

/cc @gferon
