### ISSUE TITLE
`Cargo.Bazel.lock` checksum is unstable when using path dependencies in cargo workspace 

### ISSUE THREAD

**Issue by liningpan** [bazelbuild/rules_rust#2016]
The `Cargo.Bazel.lock` files produced on mac vs linux are byte-to-byte the same except for the checksum. Could you point me to where this checksum is calculated? Is this expected or a bug? I'm currently using `rules_rust 0.23.0`.

**Comment by liningpan** [comment]
stable 1.70

**Comment by UebelAndre** [comment]
I've seen some funny business with calculating checksums before:
https://github.com/bazelbuild/rules_rust/blob/0.23.0/crate_universe/src/lockfile.rs#L150-L166

Was this issue reintroduced? Are you able to diff the metadata files generated during splicing?

**Comment by liningpan** [comment]
I figured out why... I'm using cargo workspace dependencies for local crates as well.  


```toml
[workspace]
members = ["crate_a", "crate_b"]

[workspace.dependencies]
crate_a = {path = "crate_a"}
```


```toml
[package]
edition.workspace = true
name = "crate_b"
version.workspace = true

[dependencies]
crate_a.workspace = true
```

The problem is `cargo_toml` will expand inherited local dependencies into absolute paths, so the hash will change if the repository is at a different location on the filesystem. 

As for potential solution, I'm not sure what the implication is if we use `from_str` or `from_slice` that doesn't call `complete_from_path`. 

https://docs.rs/cargo_toml/latest/cargo_toml/struct.Manifest.html#method.from_str
https://docs.rs/cargo_toml/latest/cargo_toml/struct.Manifest.html#method.from_path
