### ISSUE TITLE
Missing crate features when `Cargo.toml` specifies `default-features = false`

### ISSUE THREAD

**Issue by pamaury** [bazelbuild/rules_rust#2262]
Whenever a crate specified in `Cargo.toml` specifies a feature flag AND `default-features = false`, rules_rust generates a rust_library with no features instead of the required features. This can cause crates to no compile. An example of such a crate is `indexmap` that depends on `hashbrown` and specifies
```toml
[dependencies.hashbrown]
version = "0.12"
default-features = false
features = ["raw"]
```
Despite this, the rust_library generated in [BUILD.hashbrown-0.12.3.bazel](https://github.com/pamaury/bugs/blob/main/rules_rust_bug/crates/BUILD.hashbrown-0.12.3.bazel) has no feature enabled.

I have a minimal reproduction of the problem [here](https://github.com/pamaury/bugs/tree/main/rules_rust_bug#mishandling-of-no_default_features) using rules_rust 0.30.0.
