### ISSUE TITLE
Support `[lints]` section in `Cargo.toml`

### ISSUE THREAD

**Issue by aaronmondal** [bazelbuild/rules_rust#2348]
The `[lints]` section has been stabilized in Cargo 0.75 which shipped with Rust 1.74.0 (https://releases.rs/docs/1.74.0/#cargo). This allows users to configure clippy via `Cargo.toml` instead of `clippy.toml` like so:

```toml
# Cargo.toml

[lints.clippy]
std_instead_of_core = "warn"
pedantic = "warn"
```

Would be cool if the clippy aspects supported this usecase.
