### ISSUE TITLE
build-dependencies are not added to `crates_repository`

### ISSUE THREAD

**Issue by bradzacher** [bazelbuild/rules_rust#3194]
I'm attempting to update our repo from `rules_rust` 0.49 to 0.57 and I'm finding that `build-dependencies` aren't emitted in the generated `crates_repository` -- causing the build to fail.

In our repo we use `crates_repository` like so:
```starlark
crates_repository(
    name = "crate_index",
    cargo_lockfile = "//:Cargo.lock",
    generate_binaries = True,
    manifests = [
        "//:Cargo.lock",
        "//path/to/unzip:Cargo.toml",
    ]
    lockfile = "//:Cargo.Bazel.lock",
)
```

<details>
<summary>One of the mainfests is a `Cargo.toml` and `BUILD.bazel` that looks like this:</summary>

```toml
[package]
name = "unzip"
version = "0.0.1"
edition = { workspace = true }
description = "..."

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
napi = { workspace = true, features = ["async"] }
napi-derive = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }
zip = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
```

```starlark
load("@crate_index//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_shared_library")
load("@rules_rust//cargo:defs.bzl", "cargo_build_script")

cargo_build_script(
    name = "build_script",
    srcs = ["build.rs"],
    deps = all_crate_deps(build = True),
)

rust_shared_library(
    name = "unzip_shared",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],
    deps = all_crate_deps() + [
        ":build_script",
    ],
)
```

</details>

<details>
<summary>And in the root `Cargo.toml` we declare the dependencies like so:</summary>

```toml
[workspace]
resolver = "2"
members = [
  "path/to/unzip",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.86"
clap = "4.5.9"
napi = "2"
napi-build = "2"
napi-derive = "2"
tokio = "1.38.1"
zip = "2.2.2"
```

</details>

It's all pretty straightforward, as far as I understand, at least.

When we repin we get a lockfile which declares all of the dependencies with their correct versions.

<details>
<summary>For example I can see `napi-build`'s entry is this:</summary>

```json
"napi-build 2.1.4": {
  "name": "napi-build",
  "version": "2.1.4",
  "package_url": "https://github.com/napi-rs/napi-rs",
  "repository": {
    "Http": {
      "url": "https://static.crates.io/crates/napi-build/2.1.4/download",
      "sha256": "db836caddef23662b94e16bf1f26c40eceb09d6aee5d5b06a7ac199320b69b19"
    }
  },
  "targets": [
    {
      "Library": {
        "crate_name": "napi_build",
        "crate_root": "src/lib.rs",
        "srcs": {
          "allow_empty": true,
          "include": [
            "**/*.rs"
          ]
        }
      }
    }
  ],
  "library_target_name": "napi_build",
  "common_attrs": {
    "compile_data_glob": [
      "**"
    ],
    "edition": "2021",
    "version": "2.1.4"
  },
  "license": "MIT",
  "license_ids": [
    "MIT"
  ],
  "license_file": null
},
```

</details>

However when we do a build we get an error like:
```
/private/var/tmp/bazel/a8584ebfb3d6ff0dfe61abfbfa5bb4d3/external/crate_index/BUILD.bazel: no such target '@@crate_index//:napi-build-2.1.4': target 'napi-build-2.1.4' not declared in package '' defined by /private/var/tmp/bazel/a8584ebfb3d6ff0dfe61abfbfa5bb4d3/external/crate_index/BUILD.bazel
```

<details>
<summary>If I hop into the specified file I can see it has the following `napi-**` aliases:</summary>

```starlark
alias(
    name = "napi-2.16.13",
    actual = "@crate_index__napi-2.16.13//:napi",
    tags = ["manual"],
)

alias(
    name = "napi",
    actual = "@crate_index__napi-2.16.13//:napi",
    tags = ["manual"],
)

alias(
    name = "napi-derive-2.16.13",
    actual = "@crate_index__napi-derive-2.16.13//:napi_derive",
    tags = ["manual"],
)

alias(
    name = "napi-derive",
    actual = "@crate_index__napi-derive-2.16.13//:napi_derive",
    tags = ["manual"],
)
```

</details>

Note that an alias for `napi-build` is _not_ defined.

Note that this isn't only happening for `napi` et al -- it's also happening for a few other `build-dependencies`.

I've done some playing around and at least I've figured out that if I declare an empty, dummy crate (with an associated `rust_binary` target) in the repo and I list the `build-dependencies` as normal `dependencies`, then this causes the aliases to be output and thus everything works correctly from there.

Is this  a bug in `rules_rust`? Or have I misconfigured something somewhere?
