### ISSUE TITLE
FR: `rust_cbindgen` rule

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#381]
This is a followup on #102

Can we get a rule for generating C/C++ header files for a `rust_library`? Ideally, this would happen automatically in case where a `rust_library` is made with `crate_type="staticlib"` and `crate_type="cdylib"`. But at the very least, an explicit rule, `rust_cbindgen` would be an awesome start.

**Comment by dfreese** [comment]
I don't think there would be opposition to including it, so PRs would be welcome, but it's not something that folks have had time to prioritize.

**Comment by GregBowyer** [comment]
I am somewhat working on this, its a little tricky in that cbindgen wants to know the deps of things.

I have some trials to see how to make it happy, in no particular order:

* Alter cbindgen to become aware of deps directly - This changes a lot of cbindgen and is maybe not the best
* Make bazel produce `Cargo.lock` files - This might work but I am not 100% sold that it is clean or fully hermetic especially if cbindgen wants to call `cargo` (problematic) or `rustc` (less problematic)
* Produce a new "driver" for cbindgen that mashes up all the dependent source. This works in test for me, but can suddenly export things in dependent crates that are not relevant to the crate you are working with.
* Force users to stub out deps as renames in `cbindgen.toml` - which works but is a bit broken IMHO

**Comment by UebelAndre** [comment]
@GregBowyer Awesome! I'll have to think about what you wrote some more but I was able to come up with something quick. What do you think of something like the following (as a **super** rough concept that I wrote up in one of my projects)
```starlark
def _rust_cbindgen_impl(ctx):
    """'rust_cbindgen' rule implementation

    Args:
        ctx: A context object that is passed to the implementation function for a rule or aspect.
    Returns:
        (list) a list of Providers
    """

    rust_lib = ctx.attr.lib
    cbindgen_bin = ctx.executable._cbindgen

    is_c = ctx.attr.lang == "c"
    is_cpp = ctx.attr.lang == "c++"
    is_swift = ctx.attr.lang == "swift"

    use_c = is_c or is_swift
    use_cpp = is_cpp

    if use_c and use_cpp:
        fail("The use of C/C++ must be mutually exclusive")

    supported_crate_types = ["cdylib", "staticlib"]
    if not rust_lib[CrateInfo].type in supported_crate_types:
        fail("Rust library '{}' of type '{}' must be one of {}".format(
            rust_lib.label,
            rust_lib[CrateInfo].type,
            supported_crate_types,
        ))

    ctx.actions.expand_template(
        template = ctx.file._config_template,
        output = ctx.outputs.config,
        substitutions = {
            "{language}": "C" if use_c else "C++",
            "{include_guard}": "INCLUDED_{}_H".format(ctx.label.name.upper()),
            "{namespace}": "namespace = \"{}\"".format(ctx.label.name) if use_cpp else "",
            "{swift_name_macro}": "",  #"swift_name_macro = \"CF_SWIFT_NAME\"" if is_swift else "",
        },
    )

    args = ctx.actions.args()
    args.add("--config")
    args.add(ctx.outputs.config)
    args.add("--output")
    args.add(ctx.outputs.out)
    args.add(rust_lib[CrateInfo].root)

    outputs = [ctx.outputs.out]

    ctx.actions.run(
        mnemonic = "RustCBindgen",
        progress_message = "Generating {} bindings for '{}'..".format(
            ctx.attr.lang.upper(),
            ctx.outputs.out.short_path,
        ),
        outputs = [ctx.outputs.out],
        executable = cbindgen_bin,
        inputs = [rust_lib[CrateInfo].root, ctx.outputs.config],
        arguments = [args],
    )

    rust_compilation_context = rust_lib[CcInfo].compilation_context

    # Add the new headers to the existing CompilationContext info
    compilation_context = cc_common.create_compilation_context(
        headers = depset(rust_compilation_context.headers.to_list() + outputs),
        defines = rust_compilation_context.defines,
        framework_includes = rust_compilation_context.framework_includes,
        includes = rust_compilation_context.includes,
        local_defines = rust_compilation_context.local_defines,
        quote_includes = rust_compilation_context.quote_includes,
        system_includes = rust_compilation_context.system_includes,
    )

    return [
        rust_lib[CrateInfo],
        rust_lib[DepInfo],
        CcInfo(
            compilation_context = compilation_context,
            linking_context = rust_lib[CcInfo].linking_context,
        ),
        DefaultInfo(
            files = depset(outputs, transitive = [rust_lib.files]),
            runfiles = ctx.runfiles(outputs, transitive_files = rust_lib.files),
        ),
    ]

rust_cbindgen = rule(
    implementation = _rust_cbindgen_impl,
    doc = (
        "TODO"
    ),
    attrs = {
        "lib": attr.label(
            providers = [CrateInfo, CcInfo],
            mandatory = True,
        ),
        "cbindgen_flags": attr.string_list(
            doc = (
                "Flags to pass directly to the bindgen executable. " +
                "See https://docs.rs/cbindgen/latest/cbindgen/ for details."
            ),
        ),
        "lang": attr.string(
            doc = "The target language of the header file C/C++",
            values = [
                "c",
                "c++",
                "swift",
                "java",
            ],
            default = "c++",
        ),
        "_config_template": attr.label(
            doc = "cbindgen configuration template.",
            default = Label("//rules:private/cbindgen.toml.template"),
            allow_single_file = True,
        ),
        "_cbindgen": attr.label(
            doc = "cbindgen dependency for generating C/C++ header files",
            default = Label("//rules/raze:cargo_bin_cbindgen"),
            executable = True,
            cfg = "host",
        ),
    },
    outputs = {
        "config": "%{name}.cbindgen.toml",
        "out": "%{name}.h",
    },
    toolchains = [
        "@io_bazel_rules_rust//bindgen:bindgen_toolchain",
        "@io_bazel_rules_rust//rust:toolchain",
    ],
)
```

**Comment by UebelAndre** [comment]
@dfreese @GregBowyer I would love to get your thoughts on the implementation above. Whenever you guys get the time 😄

**Comment by UebelAndre** [comment]
Oh, I didn't realize #116 had already been posted

**Comment by dfreese** [comment]
@UebelAndre at a first pass it seems reasonable, but given the length of the toml template file, there's probably a fair bit of complexity that I could be overlooking.

**Comment by UebelAndre** [comment]
@dfreese I haven't done anything too crazy with it. It's more or less a copy/paste of the template from the [cbindgen github](https://github.com/eqrion/cbindgen/blob/master/template.toml)
```toml
# This is a template cbindgen.toml file with all of the default values.
# Some values are commented out because their absence is the real default.
#
# See https://github.com/eqrion/cbindgen/blob/master/docs.md#cbindgentoml
# for detailed documentation of every option here.

language = "{language}"

############## Options for Wrapping the Contents of the Header #################

# header = "/* Text to put at the beginning of the generated file. Probably a license. */"
# trailer = "/* Text to put at the end of the generated file */"
include_guard = "{include_guard}"
# pragma_once = true
autogen_warning = "/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */"
include_version = false
{namespace}
namespaces = []
using_namespaces = []
sys_includes = []
includes = []
no_includes = false
cpp_compat = true
after_includes = ""


############################ Code Style Options ################################

braces = "NextLine"
line_length = 120
tab_width = 4
documentation_style = "auto"


############################# Codegen Options ##################################

style = "both"


[defines]
# "target_os = freebsd" = "DEFINE_FREEBSD"
# "feature = serde" = "DEFINE_SERDE"


[export]
include = []
exclude = []
# prefix = "CAPI_"
item_types = []
renaming_overrides_prefixing = false


[export.rename]


[export.body]


[fn]
rename_args = "None"
# must_use = "MUST_USE_FUNC"
# prefix = "START_FUNC"
# postfix = "END_FUNC"
args = "auto"
sort_by = "Name"


[struct]
rename_fields = "None"
# must_use = "MUST_USE_STRUCT"
derive_constructor = false
derive_eq = false
derive_neq = false
derive_lt = false
derive_lte = false
derive_gt = false
derive_gte = false


[enum]
rename_variants = "None"
# must_use = "MUST_USE_ENUM"
add_sentinel = false
prefix_with_name = false
derive_helper_methods = false
derive_const_casts = false
derive_mut_casts = false
# cast_assert_name = "ASSERT"
derive_tagged_enum_destructor = false
derive_tagged_enum_copy_constructor = false
enum_class = true
private_default_tagged_enum_constructor = false


[const]
allow_static_const = true
allow_constexpr = true


[macro_expansion]
bitflags = false

############## Options for How Your Rust library Should Be Parsed ##############

[parse]
parse_deps = false
# include = []
exclude = []
clean = false
extra_bindings = []


[parse.expand]
crates = []
all_features = false
default_features = true
features = []
```
(apologize for the lengthy post)
